name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    name: build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install mdbook
        run: |
          tag=$(curl -LsSf https://api.github.com/repos/rust-lang/mdBook/releases/latest | jq -r '.tag_name')
          curl -LsSf https://github.com/rust-lang/mdBook/releases/download/$tag/mdbook-$tag-x86_64-unknown-linux-gnu.tar.gz | tar xzf -
          echo $(pwd) >> $GITHUB_PATH
      - run: mdbook build
      - uses: rust-lang/simpleinfra/github-actions/static-websites@master
        with:
          deploy_dir: book
          github_token: ${{ secrets.GITHUB_TOKEN }}
        if: github.event_name == 'push' && github.ref == 'refs/heads/master' && github.repository_owner == 'rust-lang'
